image: docker

services:
- docker:dind

stages:
  - test

job_test:
  stage: test
  script:
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - docker-compose up -d --build
