image: docker:git

services:
- docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

before_script:
- apk add --update python py-pip python-dev && pip install docker-compose

stages:
  - test

job_test:
  stage: test
  script:
    - docker-compose up
