image: docker/compose:latest

services:
- docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

stages:
  - test

job_test:
  stage: test
  script:
    - docker-compose up
