build:
  stage: build 
  image: 
    name: docker/compose:1.21.2
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:dind
  script:
    - docker version # verify docker cli is there. Also prints server info 
    - docker-compose version # verify the docker-compose cli is there
    - docker-compose up -d --build # building containers
    - docker-compose run app sh -c "pytest && flake8"
    - docker-compose down
