version: "3"

services:

  app:
    build:
      context: .
    image: skaben:latest
    volumes:
      - ./app:/app
      - ./logs/django:/logs
      - ./static:/static
    command: >
      sh -c "python manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=skaben
      - DB_USER=postgres
      - DB_PASS=superpass123
      - REDIS_HOST=redis
      - REDIS_PORT=5379
      - REDIS_AUTH_USER=skaben_red
      - REDIS_AUTH_PASS=superpass
      - DJANGO_SETTINGS_MODULE=app.settings.devel
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - core_network

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=skaben
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superpass123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - core_network

volumes:
  pgdata: {}

networks:
  core_network:
    driver: bridge
