[tool.vulture]
exclude = ["wsgi.py", "static/", "templates/"]
min_confidence = 80
sort_by_size = true

[tool.ruff]
line-length = 120
exclude = [
    ".venv",
    "*/migrations/*",
    "docker_build",
    ".pytest_cache",
    "static",
    "templates"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "server.settings"
