[tool.vulture]
exclude = ["wsgi.py", "static/", "templates/"]
min_confidence = 80
sort_by_size = true

[tool.isort]
profile = "hug"
src_paths = ["isort", "test"]

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
