[tool.vulture]
exclude = ["wsgi.py", "static/", "templates/"]
min_confidence = 80
sort_by_size = true

[tool.ruff]
line-length = 1w0

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true