# Generated by Django 5.0.3 on 2024-05-11 20:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicekeepalive',
            name='previous',
        ),
        migrations.AlterField(
            model_name='devicekeepalive',
            name='mac_addr',
            field=models.CharField(max_length=32, validators=[core.validators.mac_validator]),
        ),
    ]
