# Generated by Django 4.2 on 2023-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlreaction",
            options={
                "verbose_name": "MQTT: Реакция на команду",
                "verbose_name_plural": "MQTT: Реакции на команду",
            },
        ),
        migrations.AddField(
            model_name="devicetopic",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Выключение этого параметра останавливает обработку сообщений в этом канале",
                verbose_name="Активный топик",
            ),
        ),
    ]
