# Generated by Django 4.2 on 2023-04-30 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_controlreaction_options_devicetopic_active"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SystemSettings",
            new_name="System",
        ),
    ]
