# Generated by Django 4.2 on 2023-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_systemsettings_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceKeepalive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.PositiveIntegerField()),
                ("mac_addr", models.CharField(max_length=32)),
            ],
        ),
    ]
