# Generated by Django 5.0.3 on 2024-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='message',
        ),
        migrations.AlterField(
            model_name='userinput',
            name='action',
            field=models.CharField(default='action', help_text='Значение будет передано в составе INFO пакета `action: <значение>`', max_length=64, unique=True, verbose_name='Передаваемое значение'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='expected',
            field=models.CharField(blank=True, default='', help_text='По этому значению может быть выполнена проверка поля `user_input` INFO пакета', max_length=128, verbose_name='Ожидаемое значение'),
        ),
    ]
