# Generated by Django 5.0.3 on 2024-05-12 14:15

import assets.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=assets.storages.OverwriteStorage(location='/media/text'), upload_to='text/'),
        ),
    ]
