# Generated by Django 5.0.3 on 2024-05-12 15:28

import assets.storages
import assets.validators.asset_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_audiofile_file_alter_imagefile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(help_text='поддерживаются .ogg, .wav, .mp3 файлы', storage=assets.storages.OverwriteStorage(location='/media/audio/'), upload_to='audio/', validators=[assets.validators.asset_validators.audio_validator]),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(help_text='поддерживаются .png, .jpg, .webp файлы', storage=assets.storages.OverwriteStorage(location='/media/image/'), upload_to='image/', validators=[assets.validators.asset_validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=assets.storages.OverwriteStorage(location='/media/text/'), upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(help_text='поддерживаются .webm, .mp4 файлы', storage=assets.storages.OverwriteStorage(location='/media/video/'), upload_to='video/', validators=[assets.validators.asset_validators.video_validator]),
        ),
    ]
