# Generated by Django 3.2 on 2021-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1619356123)),
                ('delivered', models.BooleanField(default=False)),
                ('channel', models.CharField(max_length=16)),
                ('topic', models.CharField(max_length=32)),
                ('command', models.CharField(max_length=16)),
                ('payload', models.TextField()),
            ],
        ),
    ]
