# Generated by Django 4.1.7 on 2023-02-25 18:06

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('uuid', models.UUIDField(default=core.helpers.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('level', models.CharField(default='info', max_length=32)),
                ('stream', models.CharField(default='root', max_length=256)),
                ('source', models.CharField(default='source', max_length=256)),
                ('message', models.JSONField()),
            ],
            options={
                'verbose_name': 'Игровое событие',
                'verbose_name_plural': 'Игровые события',
            },
        ),
    ]
