# Generated by Django 3.2 on 2021-04-25 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alert', '0001_initial'),
        ('assets', '0001_initial'),
        ('device', '0001_initial'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Настройки: (Замок) код - данные карты',
                'verbose_name_plural': 'Настройки: (Замок) код - данные карты',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='menu action', max_length=48)),
                ('timer', models.IntegerField(default=-1)),
                ('option', models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image'), ('text', 'text'), ('game', 'game'), ('user', 'input')], default='user', max_length=32)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.audiofile')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.hackgame')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.imagefile')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.textfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.userinput')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.videofile')),
            ],
            options={
                'verbose_name': 'Настройки: (Терминал) элемент меню',
                'verbose_name_plural': 'Настройки: (Терминал) элементы меню',
            },
        ),
        migrations.CreateModel(
            name='WorkMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='terminal mode', max_length=48)),
                ('header', models.CharField(default='terminal vt40k', max_length=48)),
                ('footer', models.CharField(default='unauthorized access is strictly prohibited', max_length=48)),
                ('menu_set', models.ManyToManyField(to='shape.MenuItem')),
                ('state', models.ManyToManyField(blank=True, to='alert.AlertState')),
            ],
            options={
                'verbose_name': 'Настройки: (Терминал) режим работы меню',
                'verbose_name_plural': 'Настройки: (Терминал) режим работы меню',
            },
        ),
        migrations.CreateModel(
            name='SimpleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField()),
                ('dev_type', models.CharField(max_length=16)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.alertstate')),
            ],
            options={
                'verbose_name': 'Конфиг пассивного устройства',
                'verbose_name_plural': 'Конфиги пассивных устройств',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shape.accesscode')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.lock')),
                ('state_id', models.ManyToManyField(to='alert.AlertState')),
            ],
            options={
                'verbose_name': 'Настройки: (Замок) код - права допуска',
                'verbose_name_plural': 'Настройки: (Замок) код - права допуска',
                'unique_together': {('card', 'lock')},
            },
        ),
    ]
