# Generated by Django 2.1.7 on 2019-03-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sk_rest', '0002_auto_20190307_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sk_rest.Card')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('value', models.IntegerField()),
                ('current', models.CharField(default='white', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField(default=1552309757)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(max_length=12)),
                ('override', models.BooleanField(default=False)),
                ('powered', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('hacked', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('lowered', models.BooleanField(default=False)),
                ('hack_attempts', models.IntegerField(default=3)),
                ('hack_length', models.IntegerField(default=4)),
                ('hack_wordcount', models.IntegerField(default=15)),
                ('menu_list', models.CharField(max_length=12)),
                ('msg_header', models.CharField(max_length=100)),
                ('msg_body', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='lock',
            name='allowed',
        ),
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552309757),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552309757),
        ),
        migrations.AddField(
            model_name='permission',
            name='lock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sk_rest.Lock'),
        ),
        migrations.AddField(
            model_name='permission',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sk_rest.State'),
        ),
        migrations.AddField(
            model_name='lock',
            name='term_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sk_rest.Terminal'),
            preserve_default=False,
        ),
    ]
