# Generated by Django 2.1.7 on 2019-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_rest', '0003_auto_20190311_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Staff card', 'verbose_name_plural': 'Staff cards'},
        ),
        migrations.AlterModelOptions(
            name='dumb',
            options={'verbose_name': 'device: RGB/Dumb', 'verbose_name_plural': 'devices: RGB/Dumbs'},
        ),
        migrations.AlterModelOptions(
            name='lock',
            options={'verbose_name': 'device: Lock', 'verbose_name_plural': 'devices: Locks'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Staff permission', 'verbose_name_plural': 'Staff permissions'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Global Alert state', 'verbose_name_plural': 'Global Alert states'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'device: Terminal', 'verbose_name_plural': 'devices: Terminals'},
        ),
        migrations.RemoveField(
            model_name='state',
            name='current',
        ),
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552310904),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552310904),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1552310904),
        ),
    ]
