# Generated by Django 2.1.7 on 2019-03-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sk_rest', '0007_auto_20190311_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552313604),
        ),
        migrations.AlterField(
            model_name='lock',
            name='term_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sk_rest.Terminal'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552313604),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1552313604),
        ),
    ]
