# Generated by Django 2.1.7 on 2019-03-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_rest', '0012_auto_20190315_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumb',
            name='descr',
            field=models.CharField(default='simple dumb', max_length=120),
        ),
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552642788),
        ),
        migrations.AlterField(
            model_name='lock',
            name='descr',
            field=models.CharField(default='simple lock', max_length=120),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552642788),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='descr',
            field=models.CharField(default='simple terminal', max_length=120),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1552642788),
        ),
    ]
