# Generated by Django 2.1.7 on 2019-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_rest', '0013_auto_20190315_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=30)),
                ('config', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='state',
            old_name='description',
            new_name='descr',
        ),
        migrations.RemoveField(
            model_name='dumb',
            name='config',
        ),
        migrations.RemoveField(
            model_name='state',
            name='value',
        ),
        migrations.AddField(
            model_name='card',
            name='short_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dumb',
            name='dev_type',
            field=models.CharField(default='rgb', max_length=50),
        ),
        migrations.AddField(
            model_name='lock',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lock',
            name='timer',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='state',
            name='bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='state',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='fg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='state',
            name='threshold',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1555596358),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1555596358),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1555596358),
        ),
    ]
