# Generated by Django 4.1.7 on 2023-02-25 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, help_text='Счетчик примет указанное значение, уровень тревоги может быть сброшен', verbose_name='Значение счетчика')),
                ('reason', models.CharField(default='reason: changed by admin', max_length=64, verbose_name='Причина изменений')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего изменения')),
            ],
            options={
                'verbose_name': 'Тревога: счетчик уровня',
                'verbose_name_plural': 'Тревога: счетчик уровня',
            },
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='название статуса')),
                ('info', models.CharField(max_length=256, verbose_name='описание статуса')),
                ('threshold', models.IntegerField(default=-1, help_text='Нижнее значение счетчика счетчика тревоги для переключения в статус. Чтобы отключить авто-переключение - выставьте отрицательное значение', verbose_name='порог срабатывания')),
                ('current', models.BooleanField(default=False, verbose_name='сейчас активен')),
                ('order', models.IntegerField(unique=True, verbose_name='цифровое обозначение статуса')),
                ('modifier', models.IntegerField(default=5, help_text='на сколько изменяется счетчик при ошибке прохождения данжа', verbose_name='модификатор счетчика')),
            ],
            options={
                'verbose_name': 'Тревога: именной статус',
                'verbose_name_plural': 'Тревога: именные статусы',
            },
        ),
    ]
