# Generated by Django 5.0.3 on 2024-04-07 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertCounter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=0,
                        help_text="Счетчик примет указанное значение, уровень тревоги может быть сброшен",
                        verbose_name="Значение счетчика",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        default="reason: changed by admin",
                        max_length=64,
                        verbose_name="Причина изменений",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тревога: счетчик уровня",
                "verbose_name_plural": "Тревога: счетчик уровня",
            },
        ),
        migrations.CreateModel(
            name="AlertState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Название статуса"
                    ),
                ),
                (
                    "info",
                    models.CharField(max_length=256, verbose_name="Описание статуса"),
                ),
                (
                    "ingame",
                    models.BooleanField(
                        default=True,
                        help_text="Будет ли статус автоматически изменяться системой счетчика тревоги, или переключиться в него можно только специальным событием или вручную. ",
                        verbose_name="Игровой статус",
                    ),
                ),
                (
                    "threshold",
                    models.IntegerField(
                        default=-1,
                        help_text="Нижнее значение счетчика счетчика тревоги для переключения в статус. Чтобы отключить авто-переключение - выставьте отрицательное значение",
                        verbose_name="Порог срабатывания ",
                    ),
                ),
                (
                    "current",
                    models.BooleanField(default=False, verbose_name="Сейчас активен"),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="используется для идентификации и упорядочивания статуса без привязки к id в БД",
                        unique=True,
                        verbose_name="Цифровой id статуса",
                    ),
                ),
                (
                    "auto_increase",
                    models.BooleanField(
                        default=False,
                        help_text="Включить автоматическое повышение тревоги со временем",
                        verbose_name="Авто-увеличение тревоги",
                    ),
                ),
                (
                    "auto_decrease",
                    models.BooleanField(
                        default=False,
                        help_text="Включить автоматическое повышение тревоги со временем",
                        verbose_name="Авто-уменьшение тревоги",
                    ),
                ),
                (
                    "counter_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Цена ошибки. Также определяет на сколько увеличится уровень со временем (settings.ALERT_COOLDOWN) автоматически.",
                        verbose_name="На сколько увеличить уровень тревоги",
                    ),
                ),
                (
                    "counter_decrease",
                    models.IntegerField(
                        default=0,
                        help_text="Насколько снизится уровень тревоги при действии. Также определяет, на сколько уменьшится уровень со временем (settings.ALERT_COOLDOWN) автоматически.",
                        verbose_name="На сколько уменьшить уровень тревоги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тревога: именной статус",
                "verbose_name_plural": "Тревога: именные статусы",
            },
        ),
    ]
