# Generated by Django 5.0.3 on 2024-04-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("alert", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="alertstate",
            name="threshold",
            field=models.IntegerField(
                default=-1,
                help_text="Нижнее значение счетчика счетчика тревоги для переключения в статус. Чтобы отключить авто-переключение - выставьте значение ingame = False",
                verbose_name="Порог срабатывания ",
            ),
        )
    ]
