# Generated by Django 5.0.3 on 2024-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_alertstate_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertstate',
            name='auto_decrease',
        ),
        migrations.RemoveField(
            model_name='alertstate',
            name='auto_increase',
        ),
        migrations.AddField(
            model_name='alertstate',
            name='auto_change',
            field=models.CharField(choices=[('increase', 'Увеличивать'), ('decrease', 'Уменьшать')], default=False, help_text='Включить автоматическое повышение или понижение тревоги со временем', verbose_name='Авто-изменение'),
        ),
        migrations.AddField(
            model_name='alertstate',
            name='auto_level',
            field=models.IntegerField(default=0, help_text='На сколько изменится уровень тревоги при авто-повышении или авто-понижении', verbose_name='Значение авто-изменения'),
        ),
        migrations.AddField(
            model_name='alertstate',
            name='auto_timeout',
            field=models.IntegerField(default=0, help_text='Частота срабатывания авто-изменения уровня в секундах', verbose_name='Таймаут авто-изменения'),
        ),
        migrations.AlterField(
            model_name='alertstate',
            name='counter_decrease',
            field=models.IntegerField(default=0, help_text='На сколько снизится уровень тревоги при удачном действии игрока.', verbose_name='Значение уменьшения'),
        ),
        migrations.AlterField(
            model_name='alertstate',
            name='counter_increase',
            field=models.IntegerField(default=0, help_text='На сколько повысится уровень тревоги при ошибке игрока.', verbose_name='Значение увеличения'),
        ),
    ]
