# Generated by Django 5.0.3 on 2024-05-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_alertstate_auto_decrease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertstate',
            name='order',
            field=models.IntegerField(help_text='используется для идентификации и упорядочивания статуса без привязки к id в БД', unique=True, verbose_name='Порядок'),
        ),
    ]
