# Generated by Django 5.0.3 on 2024-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0003_alertstate_auto_decrease_alertstate_auto_increase"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertstate",
            name="ingame",
            field=models.BooleanField(
                default=True,
                help_text="Будет ли статус автоматически изменяться системой счетчика тревоги, или переключиться в него можно только специальным событием или вручную. ",
                verbose_name="Игровой статус",
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="current",
            field=models.BooleanField(default=False, verbose_name="Сейчас активен"),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="info",
            field=models.CharField(max_length=256, verbose_name="Описание статуса"),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="modifier",
            field=models.IntegerField(
                default=5,
                help_text="на сколько изменяется счетчик при ошибке прохождения данжа",
                verbose_name="Штраф за ошибку",
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="name",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Название статуса"
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="order",
            field=models.IntegerField(
                help_text="используется для идентификации и упорядочивания статуса без привязки к id в БД",
                unique=True,
                verbose_name="Цифровой id статуса",
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="threshold",
            field=models.IntegerField(
                default=-1,
                help_text="Нижнее значение счетчика счетчика тревоги для переключения в статус. Чтобы отключить авто-переключение - выставьте отрицательное значение",
                verbose_name="Порог срабатывания ",
            ),
        ),
    ]
