# Generated by Django 5.0.3 on 2024-04-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0004_alertstate_ingame_alter_alertstate_current_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alertcounter",
            old_name="reason",
            new_name="comment",
        ),
    ]
