# Generated by Django 5.0.3 on 2024-04-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0005_rename_reason_alertcounter_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertstate",
            name="modifier",
        ),
        migrations.AddField(
            model_name="alertstate",
            name="counter_decrease",
            field=models.IntegerField(
                default=0,
                help_text="Насколько снизится уровень тревоги при действии. Также определяет, на сколько уменьшится уровень со временем (settings.ALERT_COOLDOWN) автоматически.",
                verbose_name="На сколько уменьшить уровень тревоги",
            ),
        ),
        migrations.AddField(
            model_name="alertstate",
            name="counter_increase",
            field=models.IntegerField(
                default=0,
                help_text="Цена ошибки. Также определяет на сколько увеличится уровень со временем (settings.ALERT_COOLDOWN) автоматически.",
                verbose_name="На сколько увеличить уровень тревоги",
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="auto_decrease",
            field=models.BooleanField(
                default=False,
                help_text="Включить автоматическое повышение тревоги со временем",
                verbose_name="Авто-уменьшение тревоги",
            ),
        ),
        migrations.AlterField(
            model_name="alertstate",
            name="auto_increase",
            field=models.BooleanField(
                default=False,
                help_text="Включить автоматическое повышение тревоги со временем",
                verbose_name="Авто-увеличение тревоги",
            ),
        ),
    ]
