# Generated by Django 3.2 on 2021-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='inputname', max_length=48, unique=True)),
                ('require', models.CharField(default='input', max_length=48)),
                ('actions', models.ManyToManyField(to='actions.Action')),
            ],
            options={
                'verbose_name': 'Обратная связь - команда',
                'verbose_name_plural': 'Обратная связь - команды',
            },
        ),
    ]
