# Generated by Django 4.2 on 2023-04-30 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peripheral_devices", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimpleDevice",
        ),
    ]
