# Generated by Django 5.0.3 on 2024-05-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripheral_behavior', '0003_lockbehavior_lockworkmode'),
        ('peripheral_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockdevice',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='lockdevice',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='lockdevice',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='lockdevice',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='terminaldevice',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='terminaldevice',
            name='powered',
        ),
        migrations.AddField(
            model_name='lockdevice',
            name='work_mode',
            field=models.ManyToManyField(to='peripheral_behavior.lockworkmode'),
        ),
    ]
