# Generated by Django 5.0.3 on 2024-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripheral_behavior', '0001_initial'),
        ('peripheral_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminaldevice',
            name='hacked',
        ),
        migrations.AddField(
            model_name='terminaldevice',
            name='account_set',
            field=models.ManyToManyField(to='peripheral_behavior.terminalaccount'),
        ),
    ]
