# Generated by Django 5.0.3 on 2024-05-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_alertstate_auto_decrease_and_more'),
        ('peripheral_devices', '0003_alter_lockdevice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, help_text='JSON-объект с конфигурацией устройства.')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('topic', models.CharField(choices=[('box', 'box'), ('rgb', 'rgb'), ('scl', 'scl'), ('pwr', 'pwr')], help_text='Канал MQTT.')),
                ('state', models.ForeignKey(blank=True, help_text='Внешний ключ на объект AlertState, представляющий текущее состояние данжа.', null=True, on_delete=django.db.models.deletion.PROTECT, to='alert.alertstate')),
            ],
            options={
                'verbose_name': 'Пассивное устройство',
                'verbose_name_plural': 'Пассивные устройства',
                'unique_together': {('state', 'topic')},
            },
        ),
    ]
