# Generated by Django 2.2.9 on 2020-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200201_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1581078768)),
                ('delivered', models.BooleanField(default=False)),
                ('channel', models.CharField(max_length=16)),
                ('topic', models.CharField(max_length=32)),
                ('command', models.CharField(max_length=16)),
                ('payload', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='terminal',
            name='menu_hacked',
            field=models.ManyToManyField(related_name='menu_hacked', to='core.MenuItem'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='menu_normal',
            field=models.ManyToManyField(related_name='menu_normal', to='core.MenuItem'),
        ),
        migrations.AlterField(
            model_name='alertcounter',
            name='timestamp',
            field=models.IntegerField(default=1581078768),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.IntegerField(default=1581078768),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1581078768),
        ),
        migrations.AlterField(
            model_name='tamed',
            name='ts',
            field=models.IntegerField(default=1581078768),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1581078768),
        ),
    ]
