# Generated by Django 3.2 on 2021-04-25 13:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=3)),
                ('wordcount', models.IntegerField(default=15)),
                ('chance', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Настройки: (Терминал) мини-игры',
                'verbose_name_plural': 'Настройки: (Терминал) мини-игр',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='filename', max_length=128)),
                ('hash', models.CharField(default='', max_length=64)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/audio'), upload_to='')),
            ],
            options={
                'verbose_name': 'файл: аудио',
                'verbose_name_plural': 'файлы: аудио',
            },
        ),
        migrations.CreateModel(
            name='HackGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=3)),
                ('difficulty', models.IntegerField(choices=[(6, 'easy'), (8, 'normal'), (10, 'medium'), (12, 'hard')], default=8)),
                ('wordcount', models.IntegerField(default=15)),
                ('chance', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Настройки: (Терминал) мини-игры Fallout Hack',
                'verbose_name_plural': 'Настройки: (Терминал) мини-игра Fallout Hack',
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='filename', max_length=128)),
                ('hash', models.CharField(default='', max_length=64)),
                ('file', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/image'), upload_to='')),
            ],
            options={
                'verbose_name': 'файл: изображения',
                'verbose_name_plural': 'файлы: изображений',
            },
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='game doc', max_length=128)),
                ('header', models.CharField(default='text document', max_length=64)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'файл: текст',
                'verbose_name_plural': 'файлы: тексты',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='filename', max_length=128)),
                ('hash', models.CharField(default='', max_length=64)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/video'), upload_to='')),
            ],
            options={
                'verbose_name': 'файл: видео',
                'verbose_name_plural': 'файлы: видео',
            },
        ),
    ]
