# Generated by Django 2.1.7 on 2019-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0005_auto_20190311_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='department',
            field=models.CharField(default='department', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='long_id',
            field=models.CharField(default='a8a7a6a5a4a3a2a1', max_length=16),
        ),
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.CharField(default='staff', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='surname',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552311733),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552311733),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1552311733),
        ),
    ]
