# Generated by Django 2.1.7 on 2019-03-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0009_auto_20190311_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552313833),
        ),
        migrations.AlterField(
            model_name='lock',
            name='term_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iface.Terminal'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552313833),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1552313833),
        ),
    ]
