# Generated by Django 2.1.7 on 2019-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iface', '0010_auto_20190311_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumb',
            name='ip',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dumb',
            name='ts',
            field=models.IntegerField(default=1552314015),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1552314015),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1552314015),
        ),
    ]
