# Generated by Django 4.1.7 on 2023-02-25 18:07

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alert", "0001_initial"),
        ("peripheral_devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkabenUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=96, verbose_name="Имя")),
                (
                    "description",
                    models.CharField(max_length=96, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Игровой пользователь",
                "verbose_name_plural": "Игровые пользователи",
            },
        ),
        migrations.CreateModel(
            name="TerminalMenuItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=core.helpers.get_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timer", models.SmallIntegerField(default=0)),
                ("description", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Пункт меню терминала",
                "verbose_name_plural": "Пункты меню терминала",
            },
        ),
        migrations.CreateModel(
            name="TerminalAccount",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=core.helpers.get_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("header", models.CharField(default="terminal vt40k", max_length=64)),
                (
                    "footer",
                    models.CharField(
                        default="unauthorized access is strictly prohibited",
                        max_length=64,
                    ),
                ),
                (
                    "menu_set",
                    models.ManyToManyField(to="peripheral_behavior.terminalmenuitem"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_behavior.skabenuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Режим (полное меню) терминала",
                "verbose_name_plural": "Режим (полное меню) терминала",
            },
        ),
        migrations.CreateModel(
            name="PassiveConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("dev_type", models.CharField(max_length=16)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alert.alertstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поведение пассивного устройства",
                "verbose_name_plural": "Поведение пассивных устройств",
            },
        ),
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Произвольный цифровой код или код карты",
                        max_length=16,
                        verbose_name="Код доступа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_behavior.skabenuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Код доступа (ключ-карта)",
                "verbose_name_plural": "Коды доступа (ключ-карты)",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_behavior.accesscode",
                    ),
                ),
                (
                    "lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_devices.lockdevice",
                    ),
                ),
                ("state_id", models.ManyToManyField(to="alert.alertstate")),
            ],
            options={
                "verbose_name": "Доступ ключ-карты (права)",
                "verbose_name_plural": "Доступы ключ-карт (права)",
                "unique_together": {("card", "lock")},
            },
        ),
    ]
