# Generated by Django 5.0.3 on 2024-04-07 16:49

import core.helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alert", "0001_initial"),
        ("peripheral_devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkabenUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=96, unique=True, verbose_name="Имя"),
                ),
                (
                    "description",
                    models.CharField(max_length=96, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Игровой пользователь",
                "verbose_name_plural": "Игровые пользователи",
            },
        ),
        migrations.CreateModel(
            name="TerminalMenuItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=core.helpers.get_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timer", models.SmallIntegerField(default=0)),
                ("description", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Пункт меню терминала",
                "verbose_name_plural": "Пункты меню терминала",
            },
        ),
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Произвольный цифровой код или код карты",
                        max_length=16,
                        unique=True,
                        verbose_name="Код доступа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_behavior.skabenuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Код доступа (ключ-карта)",
                "verbose_name_plural": "Коды доступа (ключ-карты)",
            },
        ),
        migrations.CreateModel(
            name="TerminalAccount",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=core.helpers.get_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("header", models.CharField(default="terminal vt40k", max_length=64)),
                (
                    "footer",
                    models.CharField(
                        default="unauthorized access is strictly prohibited",
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_behavior.skabenuser",
                    ),
                ),
                (
                    "menu_set",
                    models.ManyToManyField(to="peripheral_behavior.terminalmenuitem"),
                ),
            ],
            options={
                "verbose_name": "Режим (полное меню) терминала",
                "verbose_name_plural": "Режим (полное меню) терминала",
            },
        ),
        migrations.CreateModel(
            name="PassiveConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON-объект с конфигурацией устройства.",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("rgb", "rgb"),
                            ("scl", "scl"),
                            ("pwr", "pwr"),
                            ("box", "box"),
                        ],
                        help_text="Канал MQTT.",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Внешний ключ на объект AlertState, представляющий текущее состояние данжа.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alert.alertstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пассивное устройство",
                "verbose_name_plural": "Пассивные устройства",
                "unique_together": {("state", "topic")},
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_behavior.accesscode",
                    ),
                ),
                (
                    "lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripheral_devices.lockdevice",
                    ),
                ),
                ("state_id", models.ManyToManyField(to="alert.alertstate")),
            ],
            options={
                "verbose_name": "Доступ ключ-карты (права)",
                "verbose_name_plural": "Доступы ключ-карт (права)",
                "unique_together": {("card", "lock")},
            },
        ),
    ]
