# Generated by Django 5.0.3 on 2024-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peripheral_behavior", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="passiveconfig",
            name="topic",
            field=models.CharField(
                choices=[("box", "box"), ("rgb", "rgb"), ("scl", "scl"), ("pwr", "pwr")], help_text="Канал MQTT."
            ),
        )
    ]
