# Generated by Django 4.2 on 2023-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peripheral_behavior", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscode",
            name="code",
            field=models.CharField(
                help_text="Произвольный цифровой код или код карты",
                max_length=16,
                unique=True,
                verbose_name="Код доступа",
            ),
        ),
        migrations.AlterField(
            model_name="skabenuser",
            name="name",
            field=models.CharField(max_length=96, unique=True, verbose_name="Имя"),
        ),
    ]
