# Generated by Django 4.2 on 2023-04-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alert", "0002_alter_alertstate_modifier_alter_alertstate_order_and_more"),
        ("peripheral_behavior", "0002_alter_accesscode_code_alter_skabenuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="passiveconfig",
            name="topic",
            field=models.CharField(
                choices=[
                    ("rgb", "rgb"),
                    ("scl", "scl"),
                    ("pwr", "pwr"),
                    ("box", "box"),
                ],
                default="rgb",
                help_text="Канал MQTT.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="passiveconfig",
            name="config",
            field=models.JSONField(
                default=dict, help_text="JSON-объект с конфигурацией устройства."
            ),
        ),
        migrations.AlterField(
            model_name="passiveconfig",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Внешний ключ на объект AlertState, представляющий текущее состояние данжа.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="alert.alertstate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="passiveconfig",
            unique_together={("state", "topic")},
        ),
        migrations.RemoveField(
            model_name="passiveconfig",
            name="dev_type",
        ),
    ]
