# Generated by Django 5.0.3 on 2024-05-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('peripheral_behavior', '0002_initial'),
        ('peripheral_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_behavior.accesscode', verbose_name='Ключ-карта'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='lock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_devices.lockdevice', verbose_name='Замок'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='state_id',
            field=models.ManyToManyField(to='alert.alertstate', verbose_name='Уровень тревоги'),
        ),
        migrations.CreateModel(
            name='TerminalMenuSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_behavior.terminalaccount', verbose_name='Аккаунт')),
                ('state_id', models.ManyToManyField(to='alert.alertstate', verbose_name='Уровень тревоги')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_devices.terminaldevice', verbose_name='Терминал')),
            ],
        ),
    ]
