# Generated by Django 5.0.3 on 2024-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripheral_behavior', '0002_alter_passiveconfig_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='passiveconfig',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
