# Generated by Django 5.0.3 on 2024-05-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('peripheral_behavior', '0002_initial'),
        ('peripheral_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.BooleanField(default=False, verbose_name='Звук замка')),
                ('closed', models.BooleanField(default=True, verbose_name='Закрыт')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('timer', models.IntegerField(default=10, verbose_name='Время автоматического закрытия')),
            ],
            options={
                'verbose_name': 'Режим: лазерная дверь',
                'verbose_name_plural': 'Режимы: лазерные двери',
            },
        ),
        migrations.CreateModel(
            name='LockWorkMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_devices.lockdevice', verbose_name='Замок')),
                ('state_id', models.ManyToManyField(to='alert.alertstate', verbose_name='Уровень тревоги')),
                ('work_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peripheral_behavior.lockbehavior', verbose_name='Режим')),
            ],
        ),
    ]
