# Generated by Django 4.2 on 2023-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peripheral_behavior",
            "0003_passiveconfig_topic_alter_passiveconfig_config_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="passiveconfig",
            name="topic",
            field=models.CharField(
                choices=[
                    ["rgb", "rgb"],
                    ["scl", "scl"],
                    ["pwr", "pwr"],
                    ["box", "box"],
                ],
                help_text="Канал MQTT.",
            ),
        ),
    ]
