# Generated by Django 2.2.6 on 2019-10-14 15:14

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Игровой код доступа',
                'verbose_name_plural': 'Игровые коды доступа',
            },
        ),
        migrations.CreateModel(
            name='AlertCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('comment', models.CharField(default='changed by admin', max_length=250)),
                ('timestamp', models.IntegerField(default=1571066095)),
            ],
            options={
                'verbose_name': 'Тревога: изменение уровня',
                'verbose_name_plural': 'Тревога: изменения уровня',
            },
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descr', models.CharField(max_length=300)),
                ('bg_color', models.CharField(default='#000000', max_length=7)),
                ('fg_color', models.CharField(default='#ffffff', max_length=7)),
                ('threshold', models.IntegerField(default=-1)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тревога: статус',
                'verbose_name_plural': 'Тревога: статусы',
            },
        ),
        migrations.CreateModel(
            name='ConfigString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_subtype', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=30)),
                ('config', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Конфиг: неуправляемые ус-ва',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('doctype', models.CharField(choices=[('img', 'image file name'), ('text', 'plain text')], default='text', max_length=50)),
                ('timer', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Игровой документ',
                'verbose_name_plural': 'Игровые документы',
            },
        ),
        migrations.CreateModel(
            name='Dumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField(default=1571066095)),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('descr', models.CharField(default='simple dumb', max_length=120)),
                ('online', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('dev_subtype', models.CharField(default='rgb', max_length=50)),
            ],
            options={
                'verbose_name': 'Устройство (пасс.): RGB ',
                'verbose_name_plural': 'Устройства (пасс.): RGB',
            },
            bases=(models.Model, core.models.DeviceMixin),
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1571066095)),
                ('message', models.CharField(default='log message', max_length=1500)),
            ],
            options={
                'verbose_name': 'Хроника событий',
                'verbose_name_plural': 'Хроника событий',
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField(default=1571066095)),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('descr', models.CharField(default='simple lock', max_length=120)),
                ('online', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('override', models.BooleanField(default=False)),
                ('sound', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('timer', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Устройство (акт.): Замок',
                'verbose_name_plural': 'Устройства (акт.): Замки',
            },
            bases=(models.Model, core.models.DeviceMixin),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=16)),
                ('callback', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'verbose_name': 'Игровой пункт меню',
                'verbose_name_plural': 'Игровые пункты меню',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField(default=1571066095)),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('descr', models.CharField(default='simple terminal', max_length=120)),
                ('online', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('override', models.BooleanField(default=False)),
                ('powered', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('block_time', models.IntegerField(default=10)),
                ('hacked', models.BooleanField(default=False)),
                ('hack_attempts', models.IntegerField(default=3)),
                ('hack_difficulty', models.IntegerField(choices=[(6, 'easy'), (8, 'normal'), (10, 'medium'), (12, 'hard')], default=6)),
                ('hack_wordcount', models.IntegerField(default=15)),
                ('hack_chance', models.IntegerField(default=10)),
                ('dev_header', models.CharField(default='terminal SK-100', max_length=100)),
                ('status_header', models.CharField(blank=True, default='', max_length=100)),
                ('document', models.ManyToManyField(blank=True, default=None, to='core.Document')),
                ('menu_hacked', models.ManyToManyField(related_name='menu_hacked', to='core.MenuItem')),
                ('menu_normal', models.ManyToManyField(related_name='menu_normal', to='core.MenuItem')),
            ],
            options={
                'verbose_name': 'Устройство (акт.): Терминал',
                'verbose_name_plural': 'Устройства (акт.): Терминалы',
            },
            bases=(models.Model, core.models.DeviceMixin),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccessCode')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lock')),
                ('state_id', models.ManyToManyField(to='core.AlertState')),
            ],
            options={
                'verbose_name': 'Игровые права доступа карт',
                'verbose_name_plural': 'Игровые права доступа карт',
                'unique_together': {('card', 'lock')},
            },
        ),
    ]
