# Generated by Django 2.2.14 on 2020-07-08 11:56

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Игровой код доступа',
                'verbose_name_plural': 'Игровые коды доступа',
            },
        ),
        migrations.CreateModel(
            name='AlertCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('comment', models.CharField(default='changed by admin', max_length=256)),
                ('timestamp', models.IntegerField(default=1594209374)),
            ],
            options={
                'verbose_name': 'Тревога: изменение уровня',
                'verbose_name_plural': 'Тревога: изменения уровня',
            },
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=256)),
                ('bg_color', models.CharField(default='#000000', max_length=7)),
                ('fg_color', models.CharField(default='#ffffff', max_length=7)),
                ('threshold', models.IntegerField(default=-1)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тревога: статус',
                'verbose_name_plural': 'Тревога: статусы',
            },
        ),
        migrations.CreateModel(
            name='AnotherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=3)),
                ('wordcount', models.IntegerField(default=15)),
                ('chance', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Настройки мини-игры',
                'verbose_name_plural': 'Настройки мини-игр',
            },
        ),
        migrations.CreateModel(
            name='ConfigString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_subtype', models.CharField(max_length=64)),
                ('state_name', models.CharField(max_length=32)),
                ('config', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Конфиг: неуправляемые ус-ва',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('doctype', models.CharField(choices=[('img', 'image file name'), ('text', 'plain text')], default='text', max_length=64)),
                ('timer', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Игровой документ',
                'verbose_name_plural': 'Игровые документы',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1594209374)),
                ('message', models.TextField()),
                ('event_type', models.CharField(default='log', max_length=32)),
            ],
            options={
                'verbose_name': 'Хроника событий',
                'verbose_name_plural': 'Хроника событий',
            },
        ),
        migrations.CreateModel(
            name='HackGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=3)),
                ('difficulty', models.IntegerField(choices=[(6, 'easy'), (8, 'normal'), (10, 'medium'), (12, 'hard')], default=6)),
                ('wordcount', models.IntegerField(default=15)),
                ('chance', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Настройки мини-игры взлома',
                'verbose_name_plural': 'Настройки мини-игр взлома',
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1594209374)),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('info', models.CharField(default='simple lock', max_length=128)),
                ('online', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('override', models.BooleanField(default=False)),
                ('sound', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('timer', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Устройство (акт.): Замок',
                'verbose_name_plural': 'Устройства (акт.): Замки',
            },
            bases=(models.Model, core.helpers.DeviceMixin),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=16)),
                ('response', models.CharField(blank=True, max_length=16)),
                ('access', models.CharField(default='10', max_length=2)),
            ],
            options={
                'verbose_name': 'Игровой пункт меню',
                'verbose_name_plural': 'Игровые пункты меню',
            },
        ),
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1594209374)),
                ('delivered', models.BooleanField(default=False)),
                ('channel', models.CharField(max_length=16)),
                ('topic', models.CharField(max_length=32)),
                ('command', models.CharField(max_length=16)),
                ('payload', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1594209374)),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('info', models.CharField(default='simple terminal', max_length=128)),
                ('online', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('override', models.BooleanField(default=False)),
                ('powered', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('block_time', models.IntegerField(default=10)),
                ('hacked', models.BooleanField(default=False)),
                ('dev_header', models.CharField(default='terminal SK-100', max_length=128)),
                ('status_header', models.CharField(blank=True, default='', max_length=128)),
                ('document', models.ManyToManyField(blank=True, default=None, to='core.Document')),
                ('menu_hacked', models.ManyToManyField(related_name='menu_hacked', to='core.MenuItem')),
                ('menu_normal', models.ManyToManyField(related_name='menu_normal', to='core.MenuItem')),
                ('mini_game', models.ManyToManyField(to='core.HackGame')),
            ],
            options={
                'verbose_name': 'Устройство (акт.): Терминал',
                'verbose_name_plural': 'Устройства (акт.): Терминалы',
            },
            bases=(models.Model, core.helpers.DeviceMixin),
        ),
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1594209374)),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('info', models.CharField(default='simple dumb', max_length=256)),
                ('online', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('subtype', models.CharField(default='rgb', max_length=32)),
                ('config', models.ManyToManyField(default='noop', to='core.ConfigString')),
            ],
            options={
                'verbose_name': 'Устройство пассивное',
                'verbose_name_plural': 'Устройства пассивные',
            },
            bases=(models.Model, core.helpers.DeviceMixin),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccessCode')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lock')),
                ('state_id', models.ManyToManyField(to='core.AlertState')),
            ],
            options={
                'verbose_name': 'Игровые права доступа карт',
                'verbose_name_plural': 'Игровые права доступа карт',
                'unique_together': {('card', 'lock')},
            },
        ),
    ]
