# Generated by Django 2.2.9 on 2020-02-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='descr',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='callback',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='menu_hacked',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='menu_normal',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='access',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='terminal',
            name='menu_items',
            field=models.ManyToManyField(to='core.MenuItem'),
        ),
        migrations.AlterField(
            model_name='alertcounter',
            name='timestamp',
            field=models.IntegerField(default=1580589155),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.IntegerField(default=1580589155),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1580589155),
        ),
        migrations.AlterField(
            model_name='tamed',
            name='ts',
            field=models.IntegerField(default=1580589155),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1580589155),
        ),
    ]
