# Generated by Django 2.2.12 on 2020-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200207_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=3)),
                ('wordcount', models.IntegerField(default=15)),
                ('chance', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Настройки мини-игры',
                'verbose_name_plural': 'Настройки мини-игр',
            },
        ),
        migrations.CreateModel(
            name='HackGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=3)),
                ('difficulty', models.IntegerField(choices=[(6, 'easy'), (8, 'normal'), (10, 'medium'), (12, 'hard')], default=6)),
                ('wordcount', models.IntegerField(default=15)),
                ('chance', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Настройки мини-игры взлома',
                'verbose_name_plural': 'Настройки мини-игр взлома',
            },
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='hack_attempts',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='hack_chance',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='hack_difficulty',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='hack_wordcount',
        ),
        migrations.AlterField(
            model_name='alertcounter',
            name='timestamp',
            field=models.IntegerField(default=1588954863),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.IntegerField(default=1588954863),
        ),
        migrations.AlterField(
            model_name='lock',
            name='ts',
            field=models.IntegerField(default=1588954863),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='timestamp',
            field=models.IntegerField(default=1588954863),
        ),
        migrations.AlterField(
            model_name='tamed',
            name='ts',
            field=models.IntegerField(default=1588954863),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ts',
            field=models.IntegerField(default=1588954863),
        ),
        migrations.AddField(
            model_name='terminal',
            name='mini_game',
            field=models.ManyToManyField(to='core.HackGame'),
        ),
    ]
