# Generated by Django 2.2.12 on 2020-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200527_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='tamed',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='ts',
        ),
        migrations.AddField(
            model_name='lock',
            name='timestamp',
            field=models.IntegerField(default=1590594083),
        ),
        migrations.AddField(
            model_name='tamed',
            name='timestamp',
            field=models.IntegerField(default=1590594083),
        ),
        migrations.AddField(
            model_name='terminal',
            name='timestamp',
            field=models.IntegerField(default=1590594083),
        ),
        migrations.AlterField(
            model_name='alertcounter',
            name='timestamp',
            field=models.IntegerField(default=1590594083),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.IntegerField(default=1590594083),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='timestamp',
            field=models.IntegerField(default=1590594083),
        ),
    ]
