# Generated by Django 2.2.12 on 2020-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200527_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(default='log', max_length=32),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='position',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='surname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='alertcounter',
            name='comment',
            field=models.CharField(default='changed by admin', max_length=256),
        ),
        migrations.AlterField(
            model_name='alertcounter',
            name='timestamp',
            field=models.IntegerField(default=1590594995),
        ),
        migrations.AlterField(
            model_name='alertstate',
            name='descr',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='alertstate',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='configstring',
            name='config',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='configstring',
            name='dev_subtype',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='configstring',
            name='state_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='doctype',
            field=models.CharField(choices=[('img', 'image file name'), ('text', 'plain text')], default='text', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='header',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.IntegerField(default=1590594995),
        ),
        migrations.AlterField(
            model_name='lock',
            name='descr',
            field=models.CharField(default='simple lock', max_length=128),
        ),
        migrations.AlterField(
            model_name='lock',
            name='timestamp',
            field=models.IntegerField(default=1590594995),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='timestamp',
            field=models.IntegerField(default=1590594995),
        ),
        migrations.AlterField(
            model_name='tamed',
            name='descr',
            field=models.CharField(default='simple dumb', max_length=256),
        ),
        migrations.AlterField(
            model_name='tamed',
            name='timestamp',
            field=models.IntegerField(default=1590594995),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='descr',
            field=models.CharField(default='simple terminal', max_length=128),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='dev_header',
            field=models.CharField(default='terminal SK-100', max_length=128),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status_header',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='timestamp',
            field=models.IntegerField(default=1590594995),
        ),
    ]
